version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch
    #volumes:
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana
    ports:
      - 5601:5601
    #volumes:
    #  - 'kibana_data:/bitnami/kibana'
    depends_on:
      - elasticsearch
#volumes:
#  elasticsearch_data:
#    driver: local
#  kibana_data:
#    driver: local
#volumes:
#  esdata1:
#    driver: local
